sudo: required
services:
  - docker

before_install:
  docker build -t sekhar92/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run sekhar92/react-test npm test -- --coverage

after_success:
  - docker build -t sekhar92/multi-client ./client
  - docker build -t sekhar92/multi-server ./server
  - docker build -t sekhar92/multi-worker ./worker
  - docker build -t sekhar92/multi-nginx ./nginx
  #Login to Dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and Push to Dockerhub
  - docker push sekhar92/multi-client
  - docker push sekhar92/multi-server
  - docker push sekhar92/multi-worker
  - docker push sekhar92/multi-nginx
  
